image: python:latest

cache:
  paths:
    - ~/.cache/pip/

before_script:
  - pip install django==3.1.4
  - pip install django-crispy-forms==1.12.0
  - pip install django-google-maps==0.12.4

build-job:
  stage: build
  script:
    - echo "Building & Testing App"
    - python3 ./manage.py test

