before script:
  - pip install -r requirements.txt

test:
  script:
    - echo "running test"
    executor: python3/default
    steps:
      run:
        command: ./manage.py test
        name: testing

      store_artifacts:
        path: test_results/
        destination: portfolio
