# Generated by Django 3.1.4 on 2021-08-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_geolocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geolocation',
        ),
    ]
