# .github/deploy.yaml

name: Deploy

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test portfolio.tests.UserTestCase

      - name: Deploy the app
        run: |
          echo "Deploying the app."